apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "asterisk.fullname" . }}
  labels:
    {{- include "asterisk.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "asterisk.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "asterisk.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: sip-tcp
              containerPort: 5060
              protocol: TCP
            - name: sip-udp
              containerPort: 5060
              protocol: UDP
            - name: rtp-10000
              containerPort: 100000
              protocol: UDP
            - name: rtp-10001
              containerPort: 100001
              protocol: UDP
            - name: rtp-10002
              containerPort: 10002
              protocol: UDP
            - name: rtp-10003
              containerPort: 10003
              protocol: UDP
            - name: rtp-10004
              containerPort: 10004
              protocol: UDP
            - name: rtp-10005
              containerPort: 10005
              protocol: UDP
            - name: rtp-10006
              containerPort: 10006
              protocol: UDP
            - name: rtp-1007
              containerPort: 10007
              protocol: UDP
            - name: rtp-10008
              containerPort: 10008
              protocol: UDP
            - name: rtp-10009
              containerPort: 10009
              protocol: UDP
            - name: rtp-10010
              containerPort: 10010
              protocol: UDP
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
